version: "3.8"
services:
  asterisk:
    build: ./asterisk
    volumes:
      - "${PWD}/asterisk/conf/:/etc/asterisk:rw"
    network_mode: host
    restart: unless-stopped
  db:
    image: postgres:16.1
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    restart: unless-stopped
volumes:
  postgres_volume:
